services:
  postgres:
    image: postgres:16
    container_name: postgres-service
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5463:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./ci/data.csv:/docker-entrypoint-initdb.d/data.csv
#      - ./ci/V1.0.0__init_schema.sql:/docker-entrypoint-initdb.d/V1.0.0__init_schema.sql
#      - ./ci/V2.0.0__add_assignment_and_question.sql:/docker-entrypoint-initdb.d/V2.0.0__add_assignment_and_question.sql
#      - ./ci/V2.0.1__add_answers_to_assignment_questions.sql:/docker-entrypoint-initdb.d/V2.0.1__add_answers_to_assignment_questions.sql
#      - ./ci/V2.0.2__add_index_for_assignment_in_question_table.sql:/docker-entrypoint-initdb.d/V2.0.2__add_index_for_assignment_in_question_table.sql
#      - ./ci/V2.0.3__add_student_answer_table.sql:/docker-entrypoint-initdb.d/V2.0.3__add_student_answer_table.sql
#      - ./ci/V99.0.0__populate_data.sql:/docker-entrypoint-initdb.d/V99.0.0__populate_data.sql
    networks:
      - app-network

#  minio:
#    image: minio/minio:latest
#    container_name: minio-service
#    restart: always
#    command: server /data --console-address ":9001"
#    environment:
#      MINIO_ROOT_USER: ${MINIO_ACCESS}
#      MINIO_ROOT_PASSWORD: ${MINIO_SECRET}
#    ports:
#      - "9003:9000"   # API
#      - "9006:9001"   # Console UI
#    volumes:
#      - minio_data:/data
#    networks:
#      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis-service
    restart: always
    ports:
      - "6380:${REDIS_PORT}"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - app-network

  app:
    build: .
#    image: bananaonthetree/backend-neurade:0.0.1
    container_name: neurade-app
    restart: always
    ports:
      - "${SERVER_HOST_PORT}:8080"
    environment:
      # ===== Database =====
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}

      # ===== MinIO =====
      MINIO_HOST: ${MINIO_HOST}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_ACCESS: ${MINIO_ACCESS}
      MINIO_SECRET: ${MINIO_SECRET}
      MINIO_BUCKET_PFP: ${MINIO_BUCKET_PFP}
      MINIO_BUCKET_CHAT: ${MINIO_BUCKET_CHAT}
      MINIO_BUCKET_ASSIGNMENT: ${MINIO_BUCKET_ASSIGNMENT}

      # ===== Redis =====
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

      # ===== LLM =====
      LLM_PROVIDER: ${LLM_PROVIDER}
      LLM_API_KEY: ${LLM_API_KEY}
      LLM_MODEL: ${LLM_MODEL}
      LLM_VALIDATE_ENDPOINT: ${LLM_VALIDATE_ENDPOINT}
      LLM_QA_ENDPOINT: ${LLM_QA_ENDPOINT}
      LLM_ASSIGNMENT_OCR_ENDPOINT: ${LLM_ASSIGNMENT_OCR_ENDPOINT}
      LLM_TOP_K: ${LLM_TOP_K}

      # ===== JWT =====
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}

      # ===== JPA =====
      JPA_DDL_AUTO: ${JPA_DDL_AUTO}
      JPA_SHOW_SQL: ${JPA_SHOW_SQL}
      JPA_FORMAT_SQL: ${JPA_FORMAT_SQL}

      # ===== ADDITIONAL SETTINGS =====
      CSV_FILE: ${CSV_FILE}

    depends_on:
      - postgres
#      - minio
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  minio_data:
  redis_data:
