spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/neurade
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket:
    pfp: neurade-pfp

gemini:
  api-key: ${GEMINI_API_KEY}

llm:
  validate-endpoint: ${LLM_VALIDATE_ENDPOINT}
application:
  security:
    jwt:
      secret-key: a2fc2b980de9ebd2351e837fb53057d389058796fcc11a01de41fcba542328bc
      expiration: 86400000 # 1 day in milliseconds
      refresh-token:
        expiration:  604800000 # 7 days in milliseconds