spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL:true}
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

minio:
  url: http://${MINIO_HOST}:${MINIO_PORT}
  access-key: ${MINIO_ACCESS}
  secret-key: ${MINIO_SECRET}
  bucket:
    pfp: ${MINIO_BUCKET_PFP:neurade-pfp}
    chat: ${MINIO_BUCKET_CHAT:neurade-chat}

llm:
  provider: ${LLM_PROVIDER:gemini}
  api-key: ${LLM_API_KEY}
  model: ${LLM_MODEL:gemini-2.5-flash}
  top-k: ${LLM_TOP_K:5}
  validate:
    endpoint: ${LLM_VALIDATE_ENDPOINT}
  qa:
    endpoint: ${LLM_QA_ENDPOINT}

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_EXPIRATION:86400000} # 1 day
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days
