CREATE TABLE ai_packages
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(100)                             NOT NULL,
    model            VARCHAR(100)                             NOT NULL,
    description      VARCHAR(1000)                            NOT NULL,
    api_keys         TEXT[]                                   NOT NULL,
    total_token      BIGINT                                   NOT NULL,
    price            DOUBLE PRECISION                         NOT NULL,
    token_rate_limit BIGINT                                   NOT NULL,
    duration_days    INTEGER                                  NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    CONSTRAINT pk_ai_packages PRIMARY KEY (id)
);

CREATE TABLE ai_packages_instances
(
    id              UUID    NOT NULL,
    ai_package_id   INTEGER NOT NULL,
    class_id        BIGINT,
    purchased_by    BIGINT  NOT NULL,
    remaining_token BIGINT  NOT NULL,
    purchase_date   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    expiry_date     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_ai_packages_instances PRIMARY KEY (id)
);

CREATE TABLE class_participants
(
    id        UUID   NOT NULL,
    class_id  BIGINT NOT NULL,
    user_id   BIGINT NOT NULL,
    joined_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_class_participants PRIMARY KEY (id)
);

CREATE TABLE classes
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(100)                            NOT NULL,
    creator_id    BIGINT                                  NOT NULL,
    description   VARCHAR(1000),
    creation_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    update_date   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_classes PRIMARY KEY (id)
);

CREATE TABLE communes
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code           VARCHAR(10)                              NOT NULL,
    name           VARCHAR(255)                             NOT NULL,
    slug           VARCHAR(255)                             NOT NULL,
    type           VARCHAR(50)                              NOT NULL,
    full_name      VARCHAR(255)                             NOT NULL,
    path           VARCHAR(500)                             NOT NULL,
    path_with_type VARCHAR(500)                             NOT NULL,
    province_code  VARCHAR                                  NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_communes PRIMARY KEY (id)
);

CREATE TABLE conversations
(
    id         VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_conversations PRIMARY KEY (id)
);

CREATE TABLE people_management
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    manager_id BIGINT                                  NOT NULL,
    managed_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_people_management PRIMARY KEY (id)
);

CREATE TABLE provinces
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code       VARCHAR(10)                              NOT NULL,
    name       VARCHAR(255)                             NOT NULL,
    slug       VARCHAR(255)                             NOT NULL,
    type       VARCHAR(50)                              NOT NULL,
    full_name  VARCHAR(255)                             NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_provinces PRIMARY KEY (id)
);

CREATE TABLE qa_entries
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    conversation_id VARCHAR(255),
    question_text   TEXT,
    answer          TEXT,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_qa_entries PRIMARY KEY (id)
);

CREATE TABLE question_assets
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    qa_entry_id BIGINT                                  NOT NULL,
    type        VARCHAR(255)                            NOT NULL,
    object_url  VARCHAR(255)                            NOT NULL,
    mime_type   VARCHAR(255)                            NOT NULL,
    order_index INTEGER                                 NOT NULL,
    CONSTRAINT pk_question_assets PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id       SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(50)                               NOT NULL,
    priority SMALLINT                                  NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE user_ai_instance_usages
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id                  BIGINT                                  NOT NULL,
    instance_id              UUID                                    NOT NULL,
    token_used               BIGINT                                  NOT NULL,
    limit_token              BIGINT,
    rate_limit_token_limit   BIGINT,
    rate_limit_token_count   BIGINT,
    rate_limit_duration_days INTEGER,
    last_reset_time          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_user_ai_instance_usages PRIMARY KEY (id)
);

CREATE TABLE user_information
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id           BIGINT                                  NOT NULL,
    first_name        VARCHAR(100),
    last_name         VARCHAR(100),
    city_code         VARCHAR                                 NOT NULL,
    sub_district_code VARCHAR,
    address_detail    VARCHAR(500),
    school            VARCHAR(255),
    grade             VARCHAR(50),
    favorite_subjects TEXT[],
    bio               VARCHAR(255),
    date_of_birth     date,
    avatar_image      VARCHAR(500),
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_user_information PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_id       SMALLINT                                NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    password_hash VARCHAR(255)                            NOT NULL,
    verified      BOOLEAN                                 NOT NULL,
    otp_id        BIGINT,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE ai_packages_instances
    ADD CONSTRAINT uc_ai_packages_instances_class UNIQUE (class_id);

ALTER TABLE ai_packages
    ADD CONSTRAINT uc_ai_packages_name UNIQUE (name);

ALTER TABLE communes
    ADD CONSTRAINT uc_communes_code UNIQUE (code);

ALTER TABLE provinces
    ADD CONSTRAINT uc_provinces_code UNIQUE (code);

ALTER TABLE user_information
    ADD CONSTRAINT uc_user_information_user UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE class_participants
    ADD CONSTRAINT uk_class_user UNIQUE (class_id, user_id);

ALTER TABLE people_management
    ADD CONSTRAINT uk_manager_managed UNIQUE (manager_id, managed_id);

CREATE INDEX idx_communes_code ON communes (code);

CREATE INDEX idx_communes_slug ON communes (slug);

CREATE INDEX idx_provinces_code ON provinces (code);

CREATE INDEX idx_provinces_slug ON provinces (slug);

CREATE INDEX idx_qa_conversation_created ON qa_entries (conversation_id, created_at DESC);

ALTER TABLE ai_packages_instances
    ADD CONSTRAINT FK_AI_PACKAGE_INSTANCE_AI_PACKAGE FOREIGN KEY (ai_package_id) REFERENCES ai_packages (id);

ALTER TABLE ai_packages_instances
    ADD CONSTRAINT FK_AI_PACKAGE_INSTANCE_CLASS FOREIGN KEY (class_id) REFERENCES classes (id);

ALTER TABLE ai_packages_instances
    ADD CONSTRAINT FK_AI_PACKAGE_INSTANCE_USER FOREIGN KEY (purchased_by) REFERENCES users (id);

ALTER TABLE classes
    ADD CONSTRAINT FK_CLASS_CREATOR FOREIGN KEY (creator_id) REFERENCES users (id);

ALTER TABLE class_participants
    ADD CONSTRAINT FK_CLASS_PARTICIPANT_CLASS FOREIGN KEY (class_id) REFERENCES classes (id);

ALTER TABLE class_participants
    ADD CONSTRAINT FK_CLASS_PARTICIPANT_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE communes
    ADD CONSTRAINT FK_COMMUNE_PROVINCE FOREIGN KEY (province_code) REFERENCES provinces (code);

CREATE INDEX idx_communes_province_code ON communes (province_code);

ALTER TABLE people_management
    ADD CONSTRAINT FK_PEOPLE_MANAGEMENT_MANAGED FOREIGN KEY (managed_id) REFERENCES users (id);

CREATE INDEX idx_managed ON people_management (managed_id);

ALTER TABLE people_management
    ADD CONSTRAINT FK_PEOPLE_MANAGEMENT_MANAGER FOREIGN KEY (manager_id) REFERENCES users (id);

CREATE INDEX idx_manager ON people_management (manager_id);

ALTER TABLE qa_entries
    ADD CONSTRAINT FK_QA_ENTRIES_ON_CONVERSATION FOREIGN KEY (conversation_id) REFERENCES conversations (id);

ALTER TABLE question_assets
    ADD CONSTRAINT FK_QUESTION_ASSET_QA_ENTRY FOREIGN KEY (qa_entry_id) REFERENCES qa_entries (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_ai_instance_usages
    ADD CONSTRAINT FK_USER_AI_INSTANCE_USAGE_AI_PACKAGE_INSTANCE FOREIGN KEY (instance_id) REFERENCES ai_packages_instances (id);

ALTER TABLE user_ai_instance_usages
    ADD CONSTRAINT FK_USER_AI_INSTANCE_USAGE_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_information
    ADD CONSTRAINT FK_USER_INFORMATION_CITY FOREIGN KEY (city_code) REFERENCES provinces (code);

CREATE INDEX idx_user_information_city_code ON user_information (city_code);

ALTER TABLE user_information
    ADD CONSTRAINT FK_USER_INFORMATION_SUB_DISTRICT FOREIGN KEY (sub_district_code) REFERENCES communes (code);

CREATE INDEX idx_user_information_sub_district_code ON user_information (sub_district_code);

ALTER TABLE user_information
    ADD CONSTRAINT FK_USER_INFORMATION_USER FOREIGN KEY (user_id) REFERENCES users (id);

CREATE INDEX idx_user_information_user_id ON user_information (user_id);